FROM node:20-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts

COPY electron ./electron
COPY server ./server
COPY package.json ./package.json

EXPOSE 3000

CMD ["npm", "run", "start:server"]
